// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BearerAPIKey provides bearerApiKey security value.
	// API Key do tenant; o scope principal está em x-viapost-scope e combinações obrigatórias em
	// x-viapost-required-scopes.
	BearerAPIKey(ctx context.Context, operationName OperationName) (BearerAPIKey, error)
}

// operationRolesBearerAPIKey is a private map storing roles per operation.
var operationRolesBearerAPIKey = map[string][]string{
	DeleteAutomationsIDOperation:                      []string{},
	DeleteContactsIDOperation:                         []string{},
	DeleteDomainsIDOperation:                          []string{},
	DeleteEventsIDOperation:                           []string{},
	DeleteSegmentsIDOperation:                         []string{},
	DeleteSegmentsIDContactsContactIDOperation:        []string{},
	DeleteTemplatesIDOperation:                        []string{},
	DeleteThemesIDOperation:                           []string{},
	DeleteWebhooksIDOperation:                         []string{},
	GetAutomationsOperation:                           []string{},
	GetAutomationsIDOperation:                         []string{},
	GetAutomationsIDRunsOperation:                     []string{},
	GetAutomationsIDRunsRunIDOperation:                []string{},
	GetContactsOperation:                              []string{},
	GetContactsIDOperation:                            []string{},
	GetDomainTrackingDomainOperation:                  []string{},
	GetDomainTrackingDomainsOperation:                 []string{},
	GetDomainsOperation:                               []string{},
	GetDomainsIDOperation:                             []string{},
	GetDomainsIDDNSOperation:                          []string{},
	GetDomainsIDHealthOperation:                       []string{},
	GetDomainsIDInboundOperation:                      []string{},
	GetEventsOperation:                                []string{},
	GetInboundMessagesOperation:                       []string{},
	GetInboundMessagesIDOperation:                     []string{},
	GetInboundMessagesIDRawOperation:                  []string{},
	GetMessagesOperation:                              []string{},
	GetMessagesEngagementOperation:                    []string{},
	GetMessagesEventsOperation:                        []string{},
	GetMessagesIDOperation:                            []string{},
	GetMessagesIDEventsOperation:                      []string{},
	GetMessagesIDRawOperation:                         []string{},
	GetMessagesMetricsOperation:                       []string{},
	GetMessagesTimeseriesOperation:                    []string{},
	GetSegmentsOperation:                              []string{},
	GetSegmentsIDOperation:                            []string{},
	GetSegmentsIDContactsOperation:                    []string{},
	GetSuppressionsOperation:                          []string{},
	GetSuppressionsExportOperation:                    []string{},
	GetSuppressionsIDOperation:                        []string{},
	GetTemplatesOperation:                             []string{},
	GetTemplatesIDOperation:                           []string{},
	GetTemplatesIDVersionsOperation:                   []string{},
	GetTemplatesIDVersionsVersionIDOperation:          []string{},
	GetThemesOperation:                                []string{},
	GetUsageOperation:                                 []string{},
	GetWebhooksOperation:                              []string{},
	GetWebhooksIDDeliveriesOperation:                  []string{},
	GetWebhooksIDDeliveriesDeliveryIDOperation:        []string{},
	PatchAutomationsIDOperation:                       []string{},
	PatchAutomationsIDDraftOperation:                  []string{},
	PatchContactsIDOperation:                          []string{},
	PatchEventsIDOperation:                            []string{},
	PatchSegmentsIDOperation:                          []string{},
	PatchTemplatesIDDraftOperation:                    []string{},
	PatchWebhooksIDOperation:                          []string{},
	PostAutomationsOperation:                          []string{},
	PostAutomationsIDActivateOperation:                []string{},
	PostAutomationsIDDisableOperation:                 []string{},
	PostAutomationsIDDuplicateOperation:               []string{},
	PostAutomationsIDRunsRunIDCancelOperation:         []string{},
	PostContactsOperation:                             []string{},
	PostContactsImportOperation:                       []string{},
	PostDomainTrackingDomainActivateOperation:         []string{},
	PostDomainTrackingDomainProofRotateOperation:      []string{},
	PostDomainTrackingDomainRevokeOperation:           []string{},
	PostDomainTrackingDomainVerifyOperation:           []string{},
	PostDomainTrackingDomainsOperation:                []string{},
	PostDomainsOperation:                              []string{},
	PostDomainsIDDkimRotateOperation:                  []string{},
	PostDomainsIDVerifyOperation:                      []string{},
	PostEventsOperation:                               []string{},
	PostEventsSendOperation:                           []string{},
	PostMessagesIDCancelOperation:                     []string{},
	PostSegmentsOperation:                             []string{},
	PostSegmentsIDContactsOperation:                   []string{},
	PostSegmentsPreviewOperation:                      []string{},
	PostSendOperation:                                 []string{},
	PostSendBatchOperation:                            []string{},
	PostSuppressionsOperation:                         []string{},
	PostSuppressionsIDReleaseOperation:                []string{},
	PostSuppressionsImportOperation:                   []string{},
	PostTemplatesOperation:                            []string{},
	PostTemplatesIDArchiveOperation:                   []string{},
	PostTemplatesIDAssetsOperation:                    []string{},
	PostTemplatesIDDuplicateOperation:                 []string{},
	PostTemplatesIDPreviewOperation:                   []string{},
	PostTemplatesIDPublishOperation:                   []string{},
	PostTemplatesIDVersionsVersionIDRevertOperation:   []string{},
	PostThemesOperation:                               []string{},
	PostWebhooksOperation:                             []string{},
	PostWebhooksIDDeliveriesDeliveryIDReplayOperation: []string{},
	PostWebhooksIDSecretRotateOperation:               []string{},
	PostWebhooksIDTestOperation:                       []string{},
}

// GetRolesForBearerAPIKey returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForBearerAPIKey(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForBearerAPIKey(operation string) []string {
	roles, ok := operationRolesBearerAPIKey[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Client) securityBearerAPIKey(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BearerAPIKey(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAPIKey\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
