// Code generated by ogen, DO NOT EDIT.
package api

type DeleteAutomationsIDRes interface {
	deleteAutomationsIDRes()
}

type DeleteContactsIDRes interface {
	deleteContactsIDRes()
}

type DeleteDomainsIDRes interface {
	deleteDomainsIDRes()
}

type DeleteEventsIDRes interface {
	deleteEventsIDRes()
}

type DeleteSegmentsIDContactsContactIDRes interface {
	deleteSegmentsIDContactsContactIDRes()
}

type DeleteSegmentsIDRes interface {
	deleteSegmentsIDRes()
}

type DeleteTemplatesIDRes interface {
	deleteTemplatesIDRes()
}

type DeleteThemesIDRes interface {
	deleteThemesIDRes()
}

type DeleteWebhooksIDRes interface {
	deleteWebhooksIDRes()
}

type GetAutomationsIDRes interface {
	getAutomationsIDRes()
}

type GetAutomationsIDRunsRes interface {
	getAutomationsIDRunsRes()
}

type GetAutomationsIDRunsRunIDRes interface {
	getAutomationsIDRunsRunIDRes()
}

type GetAutomationsRes interface {
	getAutomationsRes()
}

type GetContactsIDRes interface {
	getContactsIDRes()
}

type GetContactsRes interface {
	getContactsRes()
}

type GetDomainsIDDNSRes interface {
	getDomainsIDDNSRes()
}

type GetDomainsIDRes interface {
	getDomainsIDRes()
}

type GetDomainsRes interface {
	getDomainsRes()
}

type GetEventsRes interface {
	getEventsRes()
}

type GetHealthReadyRes interface {
	getHealthReadyRes()
}

type GetHealthRes interface {
	getHealthRes()
}

type GetInboundMessagesIDRes interface {
	getInboundMessagesIDRes()
}

type GetInboundMessagesRes interface {
	getInboundMessagesRes()
}

type GetMessagesEngagementRes interface {
	getMessagesEngagementRes()
}

type GetMessagesIDEventsRes interface {
	getMessagesIDEventsRes()
}

type GetMessagesIDRes interface {
	getMessagesIDRes()
}

type GetMessagesMetricsRes interface {
	getMessagesMetricsRes()
}

type GetMessagesRes interface {
	getMessagesRes()
}

type GetMessagesTimeseriesRes interface {
	getMessagesTimeseriesRes()
}

type GetPublicStatusRes interface {
	getPublicStatusRes()
}

type GetSegmentsIDContactsRes interface {
	getSegmentsIDContactsRes()
}

type GetSegmentsIDRes interface {
	getSegmentsIDRes()
}

type GetSegmentsRes interface {
	getSegmentsRes()
}

type GetTemplatesIDRes interface {
	getTemplatesIDRes()
}

type GetTemplatesIDVersionsRes interface {
	getTemplatesIDVersionsRes()
}

type GetTemplatesIDVersionsVersionIDRes interface {
	getTemplatesIDVersionsVersionIDRes()
}

type GetTemplatesRes interface {
	getTemplatesRes()
}

type GetThemesRes interface {
	getThemesRes()
}

type GetUsageRes interface {
	getUsageRes()
}

type GetWebhooksRes interface {
	getWebhooksRes()
}

type HeadPublicStatusRes interface {
	headPublicStatusRes()
}

type PatchAutomationsIDDraftRes interface {
	patchAutomationsIDDraftRes()
}

type PatchAutomationsIDRes interface {
	patchAutomationsIDRes()
}

type PatchContactsIDRes interface {
	patchContactsIDRes()
}

type PatchEventsIDRes interface {
	patchEventsIDRes()
}

type PatchSegmentsIDRes interface {
	patchSegmentsIDRes()
}

type PatchTemplatesIDDraftRes interface {
	patchTemplatesIDDraftRes()
}

type PostAutomationsIDActivateRes interface {
	postAutomationsIDActivateRes()
}

type PostAutomationsIDDisableRes interface {
	postAutomationsIDDisableRes()
}

type PostAutomationsIDDuplicateRes interface {
	postAutomationsIDDuplicateRes()
}

type PostAutomationsIDRunsRunIDCancelRes interface {
	postAutomationsIDRunsRunIDCancelRes()
}

type PostAutomationsRes interface {
	postAutomationsRes()
}

type PostContactsRes interface {
	postContactsRes()
}

type PostDomainsIDDkimRotateRes interface {
	postDomainsIDDkimRotateRes()
}

type PostDomainsIDVerifyRes interface {
	postDomainsIDVerifyRes()
}

type PostDomainsRes interface {
	postDomainsRes()
}

type PostEventsRes interface {
	postEventsRes()
}

type PostEventsSendRes interface {
	postEventsSendRes()
}

type PostSegmentsIDContactsRes interface {
	postSegmentsIDContactsRes()
}

type PostSegmentsRes interface {
	postSegmentsRes()
}

type PostSendRes interface {
	postSendRes()
}

type PostTemplatesIDArchiveRes interface {
	postTemplatesIDArchiveRes()
}

type PostTemplatesIDAssetsRes interface {
	postTemplatesIDAssetsRes()
}

type PostTemplatesIDDuplicateRes interface {
	postTemplatesIDDuplicateRes()
}

type PostTemplatesIDPreviewRes interface {
	postTemplatesIDPreviewRes()
}

type PostTemplatesIDPublishRes interface {
	postTemplatesIDPublishRes()
}

type PostTemplatesIDVersionsVersionIDRevertRes interface {
	postTemplatesIDVersionsVersionIDRevertRes()
}

type PostTemplatesRes interface {
	postTemplatesRes()
}

type PostThemesRes interface {
	postThemesRes()
}

type PostWebhooksRes interface {
	postWebhooksRes()
}
