// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *SegmentPreviewRequest) setDefaults() {
	{
		val := int(20)
		s.Limit.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SendRequest) setDefaults() {
	{
		val := SendRequestStream("transactional")
		s.Stream.SetTo(val)
	}
}
