// Code generated by ogen, DO NOT EDIT.
package api

type DeleteAutomationsIDRes interface {
	deleteAutomationsIDRes()
}

type DeleteContactsIDRes interface {
	deleteContactsIDRes()
}

type DeleteDomainsIDRes interface {
	deleteDomainsIDRes()
}

type DeleteEventsIDRes interface {
	deleteEventsIDRes()
}

type DeleteSegmentsIDContactsContactIDRes interface {
	deleteSegmentsIDContactsContactIDRes()
}

type DeleteSegmentsIDRes interface {
	deleteSegmentsIDRes()
}

type DeleteTemplatesIDRes interface {
	deleteTemplatesIDRes()
}

type DeleteThemesIDRes interface {
	deleteThemesIDRes()
}

type DeleteWebhooksIDRes interface {
	deleteWebhooksIDRes()
}

type GetAutomationsIDRes interface {
	getAutomationsIDRes()
}

type GetAutomationsIDRunsRes interface {
	getAutomationsIDRunsRes()
}

type GetAutomationsIDRunsRunIDRes interface {
	getAutomationsIDRunsRunIDRes()
}

type GetAutomationsRes interface {
	getAutomationsRes()
}

type GetContactsIDRes interface {
	getContactsIDRes()
}

type GetContactsRes interface {
	getContactsRes()
}

type GetDomainTrackingDomainRes interface {
	getDomainTrackingDomainRes()
}

type GetDomainTrackingDomainsRes interface {
	getDomainTrackingDomainsRes()
}

type GetDomainsIDDNSRes interface {
	getDomainsIDDNSRes()
}

type GetDomainsIDHealthRes interface {
	getDomainsIDHealthRes()
}

type GetDomainsIDInboundRes interface {
	getDomainsIDInboundRes()
}

type GetDomainsIDRes interface {
	getDomainsIDRes()
}

type GetDomainsRes interface {
	getDomainsRes()
}

type GetEventsRes interface {
	getEventsRes()
}

type GetHealthReadyRes interface {
	getHealthReadyRes()
}

type GetHealthRes interface {
	getHealthRes()
}

type GetInboundMessagesIDRawRes interface {
	getInboundMessagesIDRawRes()
}

type GetInboundMessagesIDRes interface {
	getInboundMessagesIDRes()
}

type GetInboundMessagesRes interface {
	getInboundMessagesRes()
}

type GetMessagesEngagementRes interface {
	getMessagesEngagementRes()
}

type GetMessagesEventsRes interface {
	getMessagesEventsRes()
}

type GetMessagesIDEventsRes interface {
	getMessagesIDEventsRes()
}

type GetMessagesIDRawRes interface {
	getMessagesIDRawRes()
}

type GetMessagesIDRes interface {
	getMessagesIDRes()
}

type GetMessagesMetricsRes interface {
	getMessagesMetricsRes()
}

type GetMessagesRes interface {
	getMessagesRes()
}

type GetMessagesTimeseriesRes interface {
	getMessagesTimeseriesRes()
}

type GetPublicStatusRes interface {
	getPublicStatusRes()
}

type GetSegmentsIDContactsRes interface {
	getSegmentsIDContactsRes()
}

type GetSegmentsIDRes interface {
	getSegmentsIDRes()
}

type GetSegmentsRes interface {
	getSegmentsRes()
}

type GetSuppressionsExportRes interface {
	getSuppressionsExportRes()
}

type GetSuppressionsIDRes interface {
	getSuppressionsIDRes()
}

type GetSuppressionsRes interface {
	getSuppressionsRes()
}

type GetTemplatesIDRes interface {
	getTemplatesIDRes()
}

type GetTemplatesIDVersionsRes interface {
	getTemplatesIDVersionsRes()
}

type GetTemplatesIDVersionsVersionIDRes interface {
	getTemplatesIDVersionsVersionIDRes()
}

type GetTemplatesRes interface {
	getTemplatesRes()
}

type GetThemesRes interface {
	getThemesRes()
}

type GetUsageRes interface {
	getUsageRes()
}

type GetWebhooksIDDeliveriesDeliveryIDRes interface {
	getWebhooksIDDeliveriesDeliveryIDRes()
}

type GetWebhooksIDDeliveriesRes interface {
	getWebhooksIDDeliveriesRes()
}

type GetWebhooksRes interface {
	getWebhooksRes()
}

type HeadPublicStatusRes interface {
	headPublicStatusRes()
}

type PatchAutomationsIDDraftRes interface {
	patchAutomationsIDDraftRes()
}

type PatchAutomationsIDRes interface {
	patchAutomationsIDRes()
}

type PatchContactsIDRes interface {
	patchContactsIDRes()
}

type PatchEventsIDRes interface {
	patchEventsIDRes()
}

type PatchSegmentsIDRes interface {
	patchSegmentsIDRes()
}

type PatchTemplatesIDDraftRes interface {
	patchTemplatesIDDraftRes()
}

type PatchWebhooksIDRes interface {
	patchWebhooksIDRes()
}

type PostAutomationsIDActivateRes interface {
	postAutomationsIDActivateRes()
}

type PostAutomationsIDDisableRes interface {
	postAutomationsIDDisableRes()
}

type PostAutomationsIDDuplicateRes interface {
	postAutomationsIDDuplicateRes()
}

type PostAutomationsIDRunsRunIDCancelRes interface {
	postAutomationsIDRunsRunIDCancelRes()
}

type PostAutomationsRes interface {
	postAutomationsRes()
}

type PostContactsImportRes interface {
	postContactsImportRes()
}

type PostContactsRes interface {
	postContactsRes()
}

type PostDomainTrackingDomainActivateRes interface {
	postDomainTrackingDomainActivateRes()
}

type PostDomainTrackingDomainProofRotateRes interface {
	postDomainTrackingDomainProofRotateRes()
}

type PostDomainTrackingDomainRevokeRes interface {
	postDomainTrackingDomainRevokeRes()
}

type PostDomainTrackingDomainVerifyRes interface {
	postDomainTrackingDomainVerifyRes()
}

type PostDomainTrackingDomainsRes interface {
	postDomainTrackingDomainsRes()
}

type PostDomainsIDDkimRotateRes interface {
	postDomainsIDDkimRotateRes()
}

type PostDomainsIDVerifyRes interface {
	postDomainsIDVerifyRes()
}

type PostDomainsRes interface {
	postDomainsRes()
}

type PostEventsRes interface {
	postEventsRes()
}

type PostEventsSendRes interface {
	postEventsSendRes()
}

type PostMessagesIDCancelRes interface {
	postMessagesIDCancelRes()
}

type PostSegmentsIDContactsRes interface {
	postSegmentsIDContactsRes()
}

type PostSegmentsPreviewRes interface {
	postSegmentsPreviewRes()
}

type PostSegmentsRes interface {
	postSegmentsRes()
}

type PostSendBatchRes interface {
	postSendBatchRes()
}

type PostSendRes interface {
	postSendRes()
}

type PostStatusSubscriptionsConfirmRes interface {
	postStatusSubscriptionsConfirmRes()
}

type PostStatusSubscriptionsRes interface {
	postStatusSubscriptionsRes()
}

type PostStatusSubscriptionsUnsubscribeRes interface {
	postStatusSubscriptionsUnsubscribeRes()
}

type PostSuppressionsIDReleaseRes interface {
	postSuppressionsIDReleaseRes()
}

type PostSuppressionsImportRes interface {
	postSuppressionsImportRes()
}

type PostSuppressionsRes interface {
	postSuppressionsRes()
}

type PostTemplatesIDArchiveRes interface {
	postTemplatesIDArchiveRes()
}

type PostTemplatesIDAssetsRes interface {
	postTemplatesIDAssetsRes()
}

type PostTemplatesIDDuplicateRes interface {
	postTemplatesIDDuplicateRes()
}

type PostTemplatesIDPreviewRes interface {
	postTemplatesIDPreviewRes()
}

type PostTemplatesIDPublishRes interface {
	postTemplatesIDPublishRes()
}

type PostTemplatesIDVersionsVersionIDRevertRes interface {
	postTemplatesIDVersionsVersionIDRevertRes()
}

type PostTemplatesRes interface {
	postTemplatesRes()
}

type PostThemesRes interface {
	postThemesRes()
}

type PostWebhooksIDDeliveriesDeliveryIDReplayRes interface {
	postWebhooksIDDeliveriesDeliveryIDReplayRes()
}

type PostWebhooksIDSecretRotateRes interface {
	postWebhooksIDSecretRotateRes()
}

type PostWebhooksIDTestRes interface {
	postWebhooksIDTestRes()
}

type PostWebhooksRes interface {
	postWebhooksRes()
}
