// Code generated by ogen, DO NOT EDIT.

package api

// DeleteAutomationsIDParams is parameters of deleteAutomationsId operation.
type DeleteAutomationsIDParams struct {
	ID string
}

// DeleteContactsIDParams is parameters of deleteContactsId operation.
type DeleteContactsIDParams struct {
	ID string
}

// DeleteDomainsIDParams is parameters of deleteDomainsId operation.
type DeleteDomainsIDParams struct {
	ID string
}

// DeleteEventsIDParams is parameters of deleteEventsId operation.
type DeleteEventsIDParams struct {
	ID string
}

// DeleteSegmentsIDParams is parameters of deleteSegmentsId operation.
type DeleteSegmentsIDParams struct {
	ID string
}

// DeleteSegmentsIDContactsContactIDParams is parameters of deleteSegmentsIdContactsContactId operation.
type DeleteSegmentsIDContactsContactIDParams struct {
	ID        string
	ContactID string
}

// DeleteTemplatesIDParams is parameters of deleteTemplatesId operation.
type DeleteTemplatesIDParams struct {
	ID string
}

// DeleteThemesIDParams is parameters of deleteThemesId operation.
type DeleteThemesIDParams struct {
	ID string
}

// DeleteWebhooksIDParams is parameters of deleteWebhooksId operation.
type DeleteWebhooksIDParams struct {
	ID string
}

// GetAutomationsParams is parameters of getAutomations operation.
type GetAutomationsParams struct {
	Status OptGetAutomationsStatus `json:",omitempty,omitzero"`
	Search OptString               `json:",omitempty,omitzero"`
}

// GetAutomationsIDParams is parameters of getAutomationsId operation.
type GetAutomationsIDParams struct {
	ID string
}

// GetAutomationsIDRunsParams is parameters of getAutomationsIdRuns operation.
type GetAutomationsIDRunsParams struct {
	ID string
	// Cursor opaco base64url retornado pela API, com desempate estável por `(created_at,id)`; timestamps
	// RFC 3339 legados também são aceitos. Não o interprete ou modifique e reutilize-o somente com os
	// mesmos filtros.
	Cursor OptString `json:",omitempty,omitzero"`
	// Máximo de itens por página; padrão 50.
	Limit  OptInt                        `json:",omitempty,omitzero"`
	Status OptGetAutomationsIDRunsStatus `json:",omitempty,omitzero"`
}

// GetAutomationsIDRunsRunIDParams is parameters of getAutomationsIdRunsRunId operation.
type GetAutomationsIDRunsRunIDParams struct {
	ID    string
	RunID string
}

// GetContactsParams is parameters of getContacts operation.
type GetContactsParams struct {
	// Cursor opaco base64url retornado pela API, com desempate estável por `(created_at,id)`; timestamps
	// RFC 3339 legados também são aceitos. Não o interprete ou modifique e reutilize-o somente com os
	// mesmos filtros.
	Cursor OptString `json:",omitempty,omitzero"`
	// Máximo de itens por página; padrão 50.
	Limit OptInt `json:",omitempty,omitzero"`
	// Busca por e-mail ou nome do contato; máximo de 200 caracteres.
	Search OptString `json:",omitempty,omitzero"`
}

// GetContactsIDParams is parameters of getContactsId operation.
type GetContactsIDParams struct {
	ID string
}

// GetDomainTrackingDomainParams is parameters of getDomainTrackingDomain operation.
type GetDomainTrackingDomainParams struct {
	DomainID         string
	TrackingDomainID string
}

// GetDomainTrackingDomainsParams is parameters of getDomainTrackingDomains operation.
type GetDomainTrackingDomainsParams struct {
	DomainID string
}

// GetDomainsIDParams is parameters of getDomainsId operation.
type GetDomainsIDParams struct {
	ID string
}

// GetDomainsIDDNSParams is parameters of getDomainsIdDns operation.
type GetDomainsIDDNSParams struct {
	ID string
}

// GetDomainsIDHealthParams is parameters of getDomainsIdHealth operation.
type GetDomainsIDHealthParams struct {
	ID string
}

// GetDomainsIDInboundParams is parameters of getDomainsIdInbound operation.
type GetDomainsIDInboundParams struct {
	ID string
}

// GetInboundMessagesParams is parameters of getInboundMessages operation.
type GetInboundMessagesParams struct {
	// Cursor RFC 3339 exclusivo; ausente ou inválido usa um instante futuro.
	Cursor OptDateTime `json:",omitempty,omitzero"`
	// Quantidade solicitada; ausente, não numérica ou não positiva usa 50.
	Limit          OptInt                      `json:",omitempty,omitzero"`
	DomainID       OptString                   `json:",omitempty,omitzero"`
	Search         OptString                   `json:",omitempty,omitzero"`
	Period         OptGetInboundMessagesPeriod `json:",omitempty,omitzero"`
	HasAttachments OptBool                     `json:",omitempty,omitzero"`
}

// GetInboundMessagesIDParams is parameters of getInboundMessagesId operation.
type GetInboundMessagesIDParams struct {
	ID string
}

// GetInboundMessagesIDRawParams is parameters of getInboundMessagesIdRaw operation.
type GetInboundMessagesIDRawParams struct {
	ID string
}

// GetMessagesParams is parameters of getMessages operation.
type GetMessagesParams struct {
	// Cursor RFC 3339 exclusivo; ausente ou inválido usa um instante futuro.
	Cursor OptDateTime `json:",omitempty,omitzero"`
	// Quantidade solicitada; ausente, não numérica ou não positiva usa 50.
	Limit    OptInt               `json:",omitempty,omitzero"`
	Status   OptString            `json:",omitempty,omitzero"`
	Search   OptString            `json:",omitempty,omitzero"`
	Period   OptGetMessagesPeriod `json:",omitempty,omitzero"`
	APIKeyID OptString            `json:",omitempty,omitzero"`
}

// GetMessagesEngagementParams is parameters of getMessagesEngagement operation.
type GetMessagesEngagementParams struct {
	// Valores não positivos ou inválidos usam 14; valores acima de 90 são limitados a 90.
	Days OptInt `json:",omitempty,omitzero"`
}

// GetMessagesEventsParams is parameters of getMessagesEvents operation.
type GetMessagesEventsParams struct {
	// Cursor opaco retornado em `next_cursor`; não deve ser interpretado ou alterado pelo cliente.
	Cursor OptString `json:",omitempty,omitzero"`
	// Quantidade máxima de eventos retornados.
	Limit OptInt `json:",omitempty,omitzero"`
	// Janela relativa ao instante da consulta; usa `24h` quando omitida.
	Period OptGetMessagesEventsPeriod `json:",omitempty,omitzero"`
	// Filtra por um único tipo outbound de entrega ou tracking.
	Type OptOutboundMessageEventType `json:",omitempty,omitzero"`
	// Filtra pelo UUID de uma mensagem pertencente ao tenant autenticado.
	MessageID OptString `json:",omitempty,omitzero"`
}

// GetMessagesIDParams is parameters of getMessagesId operation.
type GetMessagesIDParams struct {
	ID string
}

// GetMessagesIDEventsParams is parameters of getMessagesIdEvents operation.
type GetMessagesIDEventsParams struct {
	ID string
}

// GetMessagesIDRawParams is parameters of getMessagesIdRaw operation.
type GetMessagesIDRawParams struct {
	ID string
}

// GetMessagesMetricsParams is parameters of getMessagesMetrics operation.
type GetMessagesMetricsParams struct {
	// Valores não positivos ou inválidos usam 14; valores acima de 90 são limitados a 90.
	Days OptInt `json:",omitempty,omitzero"`
	// Filtra as métricas, inclusive `deliverability`, pelo UUID do domínio remetente.
	DomainID OptString `json:",omitempty,omitzero"`
}

// GetMessagesTimeseriesParams is parameters of getMessagesTimeseries operation.
type GetMessagesTimeseriesParams struct {
	// Valores não positivos ou inválidos usam 14; valores acima de 90 são limitados a 90.
	Days OptInt `json:",omitempty,omitzero"`
}

// GetSegmentsParams is parameters of getSegments operation.
type GetSegmentsParams struct {
	// Cursor opaco base64url retornado pela API, com desempate estável por `(created_at,id)`; timestamps
	// RFC 3339 legados também são aceitos. Não o interprete ou modifique e reutilize-o somente com os
	// mesmos filtros.
	Cursor OptString `json:",omitempty,omitzero"`
	// Máximo de itens por página; padrão 50.
	Limit OptInt `json:",omitempty,omitzero"`
	// Busca pelo nome do segmento; máximo de 200 caracteres.
	Search OptString `json:",omitempty,omitzero"`
}

// GetSegmentsIDParams is parameters of getSegmentsId operation.
type GetSegmentsIDParams struct {
	ID string
}

// GetSegmentsIDContactsParams is parameters of getSegmentsIdContacts operation.
type GetSegmentsIDContactsParams struct {
	ID string
	// Cursor opaco base64url retornado pela API, com desempate estável por `(created_at,id)`; timestamps
	// RFC 3339 legados também são aceitos. Não o interprete ou modifique e reutilize-o somente com os
	// mesmos filtros.
	Cursor OptString `json:",omitempty,omitzero"`
	// Máximo de itens por página; padrão 50.
	Limit OptInt `json:",omitempty,omitzero"`
	// Busca pelo e-mail do contato; máximo de 200 caracteres.
	Search OptString `json:",omitempty,omitzero"`
}

// GetSuppressionsParams is parameters of getSuppressions operation.
type GetSuppressionsParams struct {
	// Cursor opaco retornado em `next_cursor`.
	Cursor OptString `json:",omitempty,omitzero"`
	Limit  OptInt    `json:",omitempty,omitzero"`
	// Busca parcial sem diferenciação de maiúsculas no endereço.
	Search OptString               `json:",omitempty,omitzero"`
	Reason OptSuppressionReason    `json:",omitempty,omitzero"`
	State  OptGetSuppressionsState `json:",omitempty,omitzero"`
	Origin OptSuppressionOrigin    `json:",omitempty,omitzero"`
}

// GetSuppressionsExportParams is parameters of getSuppressionsExport operation.
type GetSuppressionsExportParams struct {
	Search OptString                     `json:",omitempty,omitzero"`
	Reason OptSuppressionReason          `json:",omitempty,omitzero"`
	State  OptGetSuppressionsExportState `json:",omitempty,omitzero"`
	Origin OptSuppressionOrigin          `json:",omitempty,omitzero"`
}

// GetSuppressionsIDParams is parameters of getSuppressionsId operation.
type GetSuppressionsIDParams struct {
	ID string
	// Cursor opaco para carregar eventos de auditoria anteriores.
	HistoryCursor OptString `json:",omitempty,omitzero"`
	// Quantidade de eventos de auditoria por página.
	HistoryLimit OptInt `json:",omitempty,omitzero"`
}

// GetTemplatesParams is parameters of getTemplates operation.
type GetTemplatesParams struct {
	// Cursor RFC 3339 exclusivo; ausente ou inválido usa um instante futuro.
	Cursor OptDateTime `json:",omitempty,omitzero"`
	// Quantidade solicitada; ausente, não numérica ou não positiva usa 50.
	Limit  OptInt    `json:",omitempty,omitzero"`
	Search OptString `json:",omitempty,omitzero"`
}

// GetTemplatesIDParams is parameters of getTemplatesId operation.
type GetTemplatesIDParams struct {
	ID string
}

// GetTemplatesIDVersionsParams is parameters of getTemplatesIdVersions operation.
type GetTemplatesIDVersionsParams struct {
	ID string
}

// GetTemplatesIDVersionsVersionIDParams is parameters of getTemplatesIdVersionsVersionId operation.
type GetTemplatesIDVersionsVersionIDParams struct {
	ID        string
	VersionID string
}

// GetWebhooksIDDeliveriesParams is parameters of getWebhooksIdDeliveries operation.
type GetWebhooksIDDeliveriesParams struct {
	ID string
	// Cursor opaco retornado em `next_cursor`.
	Cursor    OptString                   `json:",omitempty,omitzero"`
	Limit     OptInt                      `json:",omitempty,omitzero"`
	Status    OptWebhookDeliveryStatus    `json:",omitempty,omitzero"`
	EventType OptWebhookDeliveryEventType `json:",omitempty,omitzero"`
}

// GetWebhooksIDDeliveriesDeliveryIDParams is parameters of getWebhooksIdDeliveriesDeliveryId operation.
type GetWebhooksIDDeliveriesDeliveryIDParams struct {
	ID         string
	DeliveryID string
}

// PatchAutomationsIDParams is parameters of patchAutomationsId operation.
type PatchAutomationsIDParams struct {
	ID string
}

// PatchAutomationsIDDraftParams is parameters of patchAutomationsIdDraft operation.
type PatchAutomationsIDDraftParams struct {
	ID string
}

// PatchContactsIDParams is parameters of patchContactsId operation.
type PatchContactsIDParams struct {
	ID string
}

// PatchEventsIDParams is parameters of patchEventsId operation.
type PatchEventsIDParams struct {
	ID string
}

// PatchSegmentsIDParams is parameters of patchSegmentsId operation.
type PatchSegmentsIDParams struct {
	ID string
}

// PatchTemplatesIDDraftParams is parameters of patchTemplatesIdDraft operation.
type PatchTemplatesIDDraftParams struct {
	ID string
}

// PatchWebhooksIDParams is parameters of patchWebhooksId operation.
type PatchWebhooksIDParams struct {
	ID string
}

// PostAutomationsIDActivateParams is parameters of postAutomationsIdActivate operation.
type PostAutomationsIDActivateParams struct {
	ID string
}

// PostAutomationsIDDisableParams is parameters of postAutomationsIdDisable operation.
type PostAutomationsIDDisableParams struct {
	ID string
}

// PostAutomationsIDDuplicateParams is parameters of postAutomationsIdDuplicate operation.
type PostAutomationsIDDuplicateParams struct {
	ID string
}

// PostAutomationsIDRunsRunIDCancelParams is parameters of postAutomationsIdRunsRunIdCancel operation.
type PostAutomationsIDRunsRunIDCancelParams struct {
	ID    string
	RunID string
}

// PostDomainTrackingDomainActivateParams is parameters of postDomainTrackingDomainActivate operation.
type PostDomainTrackingDomainActivateParams struct {
	DomainID         string
	TrackingDomainID string
}

// PostDomainTrackingDomainProofRotateParams is parameters of postDomainTrackingDomainProofRotate operation.
type PostDomainTrackingDomainProofRotateParams struct {
	DomainID         string
	TrackingDomainID string
}

// PostDomainTrackingDomainRevokeParams is parameters of postDomainTrackingDomainRevoke operation.
type PostDomainTrackingDomainRevokeParams struct {
	DomainID         string
	TrackingDomainID string
}

// PostDomainTrackingDomainVerifyParams is parameters of postDomainTrackingDomainVerify operation.
type PostDomainTrackingDomainVerifyParams struct {
	DomainID         string
	TrackingDomainID string
}

// PostDomainTrackingDomainsParams is parameters of postDomainTrackingDomains operation.
type PostDomainTrackingDomainsParams struct {
	DomainID string
}

// PostDomainsIDDkimRotateParams is parameters of postDomainsIdDkimRotate operation.
type PostDomainsIDDkimRotateParams struct {
	ID string
}

// PostDomainsIDVerifyParams is parameters of postDomainsIdVerify operation.
type PostDomainsIDVerifyParams struct {
	ID string
}

// PostEventsSendParams is parameters of postEventsSend operation.
type PostEventsSendParams struct {
	// Chave opcional por tenant; espaços nas pontas são removidos e valor vazio equivale à ausência. O
	// schema ativo do evento é revalidado antes da consulta à chave, portanto mesmo uma repetição
	// idêntica pode retornar 400 após mudança de schema. Se a validação passar, conteúdo divergente
	// para a mesma chave retorna 409.
	IdempotencyKey OptString `json:",omitempty,omitzero"`
}

// PostMessagesIDCancelParams is parameters of postMessagesIdCancel operation.
type PostMessagesIDCancelParams struct {
	ID string
}

// PostSegmentsIDContactsParams is parameters of postSegmentsIdContacts operation.
type PostSegmentsIDContactsParams struct {
	ID string
}

// PostSendParams is parameters of postSend operation.
type PostSendParams struct {
	IdempotencyKey OptString `json:",omitempty,omitzero"`
}

// PostSuppressionsIDReleaseParams is parameters of postSuppressionsIdRelease operation.
type PostSuppressionsIDReleaseParams struct {
	ID string
}

// PostTemplatesIDArchiveParams is parameters of postTemplatesIdArchive operation.
type PostTemplatesIDArchiveParams struct {
	ID string
}

// PostTemplatesIDAssetsParams is parameters of postTemplatesIdAssets operation.
type PostTemplatesIDAssetsParams struct {
	ID string
}

// PostTemplatesIDDuplicateParams is parameters of postTemplatesIdDuplicate operation.
type PostTemplatesIDDuplicateParams struct {
	ID string
}

// PostTemplatesIDPreviewParams is parameters of postTemplatesIdPreview operation.
type PostTemplatesIDPreviewParams struct {
	ID string
}

// PostTemplatesIDPublishParams is parameters of postTemplatesIdPublish operation.
type PostTemplatesIDPublishParams struct {
	ID string
}

// PostTemplatesIDVersionsVersionIDRevertParams is parameters of postTemplatesIdVersionsVersionIdRevert operation.
type PostTemplatesIDVersionsVersionIDRevertParams struct {
	ID        string
	VersionID string
}

// PostWebhooksIDDeliveriesDeliveryIDReplayParams is parameters of postWebhooksIdDeliveriesDeliveryIdReplay operation.
type PostWebhooksIDDeliveriesDeliveryIDReplayParams struct {
	ID         string
	DeliveryID string
	// Identifica uma operação de escrita. Deve ser reutilizada apenas ao repetir exatamente a mesma
	// solicitação; uso conflitante retorna `409`.
	IdempotencyKey string
}

// PostWebhooksIDSecretRotateParams is parameters of postWebhooksIdSecretRotate operation.
type PostWebhooksIDSecretRotateParams struct {
	ID string
	// Identifica uma operação de escrita. Deve ser reutilizada apenas ao repetir exatamente a mesma
	// solicitação; uso conflitante retorna `409`.
	IdempotencyKey string
}

// PostWebhooksIDTestParams is parameters of postWebhooksIdTest operation.
type PostWebhooksIDTestParams struct {
	ID string
	// Identifica uma operação de escrita. Deve ser reutilizada apenas ao repetir exatamente a mesma
	// solicitação; uso conflitante retorna `409`.
	IdempotencyKey string
}
