// Code generated by ogen, DO NOT EDIT.

package api

// DeleteAutomationsIDParams is parameters of deleteAutomationsId operation.
type DeleteAutomationsIDParams struct {
	ID string
}

// DeleteContactsIDParams is parameters of deleteContactsId operation.
type DeleteContactsIDParams struct {
	ID string
}

// DeleteDomainsIDParams is parameters of deleteDomainsId operation.
type DeleteDomainsIDParams struct {
	ID string
}

// DeleteEventsIDParams is parameters of deleteEventsId operation.
type DeleteEventsIDParams struct {
	ID string
}

// DeleteSegmentsIDParams is parameters of deleteSegmentsId operation.
type DeleteSegmentsIDParams struct {
	ID string
}

// DeleteSegmentsIDContactsContactIDParams is parameters of deleteSegmentsIdContactsContactId operation.
type DeleteSegmentsIDContactsContactIDParams struct {
	ID        string
	ContactID string
}

// DeleteTemplatesIDParams is parameters of deleteTemplatesId operation.
type DeleteTemplatesIDParams struct {
	ID string
}

// DeleteThemesIDParams is parameters of deleteThemesId operation.
type DeleteThemesIDParams struct {
	ID string
}

// DeleteWebhooksIDParams is parameters of deleteWebhooksId operation.
type DeleteWebhooksIDParams struct {
	ID string
}

// GetAutomationsParams is parameters of getAutomations operation.
type GetAutomationsParams struct {
	Status OptGetAutomationsStatus `json:",omitempty,omitzero"`
	Search OptString               `json:",omitempty,omitzero"`
}

// GetAutomationsIDParams is parameters of getAutomationsId operation.
type GetAutomationsIDParams struct {
	ID string
}

// GetAutomationsIDRunsParams is parameters of getAutomationsIdRuns operation.
type GetAutomationsIDRunsParams struct {
	ID string
	// Cursor opaco base64url retornado pela API; timestamps RFC 3339 legados também são aceitos.
	Cursor OptString                     `json:",omitempty,omitzero"`
	Limit  OptInt                        `json:",omitempty,omitzero"`
	Status OptGetAutomationsIDRunsStatus `json:",omitempty,omitzero"`
}

// GetAutomationsIDRunsRunIDParams is parameters of getAutomationsIdRunsRunId operation.
type GetAutomationsIDRunsRunIDParams struct {
	ID    string
	RunID string
}

// GetContactsParams is parameters of getContacts operation.
type GetContactsParams struct {
	// Cursor opaco base64url retornado pela API; timestamps RFC 3339 legados também são aceitos.
	Cursor OptString `json:",omitempty,omitzero"`
	Limit  OptInt    `json:",omitempty,omitzero"`
	Search OptString `json:",omitempty,omitzero"`
}

// GetContactsIDParams is parameters of getContactsId operation.
type GetContactsIDParams struct {
	ID string
}

// GetDomainsIDParams is parameters of getDomainsId operation.
type GetDomainsIDParams struct {
	ID string
}

// GetDomainsIDDNSParams is parameters of getDomainsIdDns operation.
type GetDomainsIDDNSParams struct {
	ID string
}

// GetInboundMessagesParams is parameters of getInboundMessages operation.
type GetInboundMessagesParams struct {
	// Cursor RFC 3339 exclusivo; ausente ou inválido usa um instante futuro.
	Cursor OptDateTime `json:",omitempty,omitzero"`
	// Quantidade solicitada; ausente, não numérica ou não positiva usa 50.
	Limit          OptInt                      `json:",omitempty,omitzero"`
	DomainID       OptString                   `json:",omitempty,omitzero"`
	Search         OptString                   `json:",omitempty,omitzero"`
	Period         OptGetInboundMessagesPeriod `json:",omitempty,omitzero"`
	HasAttachments OptBool                     `json:",omitempty,omitzero"`
}

// GetInboundMessagesIDParams is parameters of getInboundMessagesId operation.
type GetInboundMessagesIDParams struct {
	ID string
}

// GetMessagesParams is parameters of getMessages operation.
type GetMessagesParams struct {
	// Cursor RFC 3339 exclusivo; ausente ou inválido usa um instante futuro.
	Cursor OptDateTime `json:",omitempty,omitzero"`
	// Quantidade solicitada; ausente, não numérica ou não positiva usa 50.
	Limit    OptInt               `json:",omitempty,omitzero"`
	Status   OptString            `json:",omitempty,omitzero"`
	Search   OptString            `json:",omitempty,omitzero"`
	Period   OptGetMessagesPeriod `json:",omitempty,omitzero"`
	APIKeyID OptString            `json:",omitempty,omitzero"`
}

// GetMessagesEngagementParams is parameters of getMessagesEngagement operation.
type GetMessagesEngagementParams struct {
	// Valores não positivos ou inválidos usam 14; valores acima de 90 são limitados a 90.
	Days OptInt `json:",omitempty,omitzero"`
}

// GetMessagesIDParams is parameters of getMessagesId operation.
type GetMessagesIDParams struct {
	ID string
}

// GetMessagesIDEventsParams is parameters of getMessagesIdEvents operation.
type GetMessagesIDEventsParams struct {
	ID string
}

// GetMessagesMetricsParams is parameters of getMessagesMetrics operation.
type GetMessagesMetricsParams struct {
	// Valores não positivos ou inválidos usam 14; valores acima de 90 são limitados a 90.
	Days     OptInt    `json:",omitempty,omitzero"`
	DomainID OptString `json:",omitempty,omitzero"`
}

// GetMessagesTimeseriesParams is parameters of getMessagesTimeseries operation.
type GetMessagesTimeseriesParams struct {
	// Valores não positivos ou inválidos usam 14; valores acima de 90 são limitados a 90.
	Days OptInt `json:",omitempty,omitzero"`
}

// GetSegmentsParams is parameters of getSegments operation.
type GetSegmentsParams struct {
	// Cursor opaco base64url retornado pela API; timestamps RFC 3339 legados também são aceitos.
	Cursor OptString `json:",omitempty,omitzero"`
	Limit  OptInt    `json:",omitempty,omitzero"`
	Search OptString `json:",omitempty,omitzero"`
}

// GetSegmentsIDParams is parameters of getSegmentsId operation.
type GetSegmentsIDParams struct {
	ID string
}

// GetSegmentsIDContactsParams is parameters of getSegmentsIdContacts operation.
type GetSegmentsIDContactsParams struct {
	ID string
	// Cursor opaco base64url retornado pela API; timestamps RFC 3339 legados também são aceitos.
	Cursor OptString `json:",omitempty,omitzero"`
	Limit  OptInt    `json:",omitempty,omitzero"`
	Search OptString `json:",omitempty,omitzero"`
}

// GetTemplatesParams is parameters of getTemplates operation.
type GetTemplatesParams struct {
	// Cursor RFC 3339 exclusivo; ausente ou inválido usa um instante futuro.
	Cursor OptDateTime `json:",omitempty,omitzero"`
	// Quantidade solicitada; ausente, não numérica ou não positiva usa 50.
	Limit  OptInt    `json:",omitempty,omitzero"`
	Search OptString `json:",omitempty,omitzero"`
}

// GetTemplatesIDParams is parameters of getTemplatesId operation.
type GetTemplatesIDParams struct {
	ID string
}

// GetTemplatesIDVersionsParams is parameters of getTemplatesIdVersions operation.
type GetTemplatesIDVersionsParams struct {
	ID string
}

// GetTemplatesIDVersionsVersionIDParams is parameters of getTemplatesIdVersionsVersionId operation.
type GetTemplatesIDVersionsVersionIDParams struct {
	ID        string
	VersionID string
}

// PatchAutomationsIDParams is parameters of patchAutomationsId operation.
type PatchAutomationsIDParams struct {
	ID string
}

// PatchAutomationsIDDraftParams is parameters of patchAutomationsIdDraft operation.
type PatchAutomationsIDDraftParams struct {
	ID string
}

// PatchContactsIDParams is parameters of patchContactsId operation.
type PatchContactsIDParams struct {
	ID string
}

// PatchEventsIDParams is parameters of patchEventsId operation.
type PatchEventsIDParams struct {
	ID string
}

// PatchSegmentsIDParams is parameters of patchSegmentsId operation.
type PatchSegmentsIDParams struct {
	ID string
}

// PatchTemplatesIDDraftParams is parameters of patchTemplatesIdDraft operation.
type PatchTemplatesIDDraftParams struct {
	ID string
}

// PostAutomationsIDActivateParams is parameters of postAutomationsIdActivate operation.
type PostAutomationsIDActivateParams struct {
	ID string
}

// PostAutomationsIDDisableParams is parameters of postAutomationsIdDisable operation.
type PostAutomationsIDDisableParams struct {
	ID string
}

// PostAutomationsIDDuplicateParams is parameters of postAutomationsIdDuplicate operation.
type PostAutomationsIDDuplicateParams struct {
	ID string
}

// PostAutomationsIDRunsRunIDCancelParams is parameters of postAutomationsIdRunsRunIdCancel operation.
type PostAutomationsIDRunsRunIDCancelParams struct {
	ID    string
	RunID string
}

// PostDomainsIDDkimRotateParams is parameters of postDomainsIdDkimRotate operation.
type PostDomainsIDDkimRotateParams struct {
	ID string
}

// PostDomainsIDVerifyParams is parameters of postDomainsIdVerify operation.
type PostDomainsIDVerifyParams struct {
	ID string
}

// PostSegmentsIDContactsParams is parameters of postSegmentsIdContacts operation.
type PostSegmentsIDContactsParams struct {
	ID string
}

// PostSendParams is parameters of postSend operation.
type PostSendParams struct {
	IdempotencyKey OptString `json:",omitempty,omitzero"`
}

// PostTemplatesIDArchiveParams is parameters of postTemplatesIdArchive operation.
type PostTemplatesIDArchiveParams struct {
	ID string
}

// PostTemplatesIDAssetsParams is parameters of postTemplatesIdAssets operation.
type PostTemplatesIDAssetsParams struct {
	ID string
}

// PostTemplatesIDDuplicateParams is parameters of postTemplatesIdDuplicate operation.
type PostTemplatesIDDuplicateParams struct {
	ID string
}

// PostTemplatesIDPreviewParams is parameters of postTemplatesIdPreview operation.
type PostTemplatesIDPreviewParams struct {
	ID string
}

// PostTemplatesIDPublishParams is parameters of postTemplatesIdPublish operation.
type PostTemplatesIDPublishParams struct {
	ID string
}

// PostTemplatesIDVersionsVersionIDRevertParams is parameters of postTemplatesIdVersionsVersionIdRevert operation.
type PostTemplatesIDVersionsVersionIDRevertParams struct {
	ID        string
	VersionID string
}
