// Code generated by internal/generate from the public OpenAPI oneOf schemas; DO NOT EDIT.
package api

import (
	"encoding/json"
	"fmt"

	"github.com/go-faster/jx"
)

// Validate checks which documented oneOf variant a segment creation request represents.
func (s CreateSegmentRequest) Validate() error {
	if err := requireSegmentFields(map[string]jx.Raw(s), "name", "description", "kind", "definition"); err != nil {
		return err
	}
	name, err := rawString(s, "name")
	if err != nil || name == "" {
		return fmt.Errorf("segment request requires non-empty name")
	}
	kind, present, err := optionalRawString(s, "kind")
	if err != nil {
		return err
	}
	if !present || kind == "static" {
		if _, ok := s["definition"]; ok {
			return fmt.Errorf("static segment request must not contain definition")
		}
		return nil
	}
	if kind != "dynamic" {
		return fmt.Errorf("segment request kind must be static or dynamic")
	}
	raw, ok := s["definition"]
	if !ok {
		return fmt.Errorf("dynamic segment request requires definition")
	}
	return validateSegmentDefinitionRaw(raw)
}

// Validate checks a segment response's static or dynamic variant without discarding its fields.
func (s Segment) Validate() error {
	if err := requireSegmentFields(map[string]jx.Raw(s), "id", "name", "description", "kind", "definition", "contact_count", "created_at", "updated_at"); err != nil {
		return err
	}
	kind, err := rawString(s, "kind")
	if err != nil {
		return err
	}
	if kind == "static" {
		if !rawIsNull(s["definition"]) {
			return fmt.Errorf("static segment definition must be null")
		}
		return nil
	}
	if kind != "dynamic" {
		return fmt.Errorf("segment kind must be static or dynamic")
	}
	return validateSegmentDefinitionRaw(s["definition"])
}

// Validate checks the all/any group union and its bounded recursive shape.
func (s SegmentDefinition) Validate() error {
	encoder := jx.Encoder{}
	s.Encode(&encoder)
	return validateSegmentDefinitionRaw(jx.Raw(encoder.Bytes()))
}

func validateSegmentDefinitionRaw(raw jx.Raw) error { return validateSegmentRule(raw, 0, true) }

func validateSegmentRule(raw jx.Raw, depth int, root bool) error {
	var node map[string]json.RawMessage
	if err := json.Unmarshal(raw, &node); err != nil {
		return fmt.Errorf("segment definition must be an object: %w", err)
	}
	if len(node) != 1 {
		return fmt.Errorf("segment rule must select exactly one variant")
	}
	for key, value := range node {
		if key == "all" || key == "any" {
			if depth >= 3 {
				return fmt.Errorf("segment definition exceeds maximum group depth")
			}
			var children []json.RawMessage
			if err := json.Unmarshal(value, &children); err != nil || len(children) == 0 || len(children) > 25 {
				return fmt.Errorf("segment %s group must contain 1 to 25 rules", key)
			}
			for _, child := range children {
				if err := validateSegmentRule(jx.Raw(child), depth+1, false); err != nil {
					return err
				}
			}
			return nil
		}
		if root {
			return fmt.Errorf("segment definition root must be an all or any group")
		}
		if !segmentLeafVariant(key) {
			return fmt.Errorf("unknown segment predicate variant %q", key)
		}
		var predicate map[string]json.RawMessage
		if err := json.Unmarshal(value, &predicate); err != nil || len(predicate) == 0 {
			return fmt.Errorf("segment predicate %q must be a non-empty object", key)
		}
		return nil
	}
	return fmt.Errorf("invalid segment rule")
}

func segmentLeafVariant(key string) bool {
	switch key {
	case "text_attribute", "text_presence", "subscribed", "created_at", "property_value", "property_presence", "custom_event":
		return true
	}
	return false
}
func rawIsNull(raw jx.Raw) bool { return string(raw) == "null" }
func rawString(values map[string]jx.Raw, key string) (string, error) {
	raw, ok := values[key]
	if !ok {
		return "", fmt.Errorf("missing segment field %q", key)
	}
	var value string
	if err := json.Unmarshal(raw, &value); err != nil {
		return "", fmt.Errorf("segment field %q must be a string", key)
	}
	return value, nil
}
func optionalRawString(values map[string]jx.Raw, key string) (string, bool, error) {
	raw, ok := values[key]
	if !ok {
		return "", false, nil
	}
	var value string
	if err := json.Unmarshal(raw, &value); err != nil {
		return "", true, fmt.Errorf("segment field %q must be a string", key)
	}
	return value, true, nil
}
func requireSegmentFields(values map[string]jx.Raw, allowed ...string) error {
	permitted := map[string]bool{}
	for _, key := range allowed {
		permitted[key] = true
	}
	for key := range values {
		if !permitted[key] {
			return fmt.Errorf("unexpected segment field %q", key)
		}
	}
	return nil
}
